services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: articles_db
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    ports:
      - '3030:5432'
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.local
      

volumes:
  db:
    driver: local